let allMusic = [
  {
    name: "The Girl I Have a Crush On",
    artist: "frad",
    img: "music-1",
    src: "music-1",
  },
  {
    name: "The Perfect Girl (Instrumental)",
    artist: "Mareux",
    img: "music-1",
    src: "The Perfect Girl (Instrumental) - Mareux",
  },
  {
    name: "Something About You",
    artist: "Eyedress & Dent May",
    img: "music-1",
    src: "Eyedress & Dent May - Something About You - David Dean Burkhart",
  },
  {
    name: "An Art Gallery Could Never Be As Unique As You",
    artist: "mrld",
    img: "music-1",
    src: "music-3",
  },
  {
    name: "It's You",
    artist: "Ali Gatie",
    img: "music-1",
    src: "Ali Gatie - It's You (Official Lyrics Video) - Ali Gatie",
  },
  {
    name: "Somebody To You",
    artist: "The Vamps",
    img: "music-1",
    src: "Somebody To You - The Vamps",
  },
  {
    name: "I Wanna Be Yours",
    artist: "Arctic Monkeys",
    img: "music-1",
    src: "Arctic Monkeys - I Wanna Be Yours - Francisco Cerón",
  },
  {
    name: "From The Start",
    artist: "Laufey",
    img: "music-1",
    src: "Laufey - From The Start (Official Music Video) - Laufey",
  },
  {
    name: "The Only Exception",
    artist: "Paramore",
    img: "music-1",
    src: "Paramore The Only Exception [OFFICIAL VIDEO] - Paramore",
  },
  {
    name: "Someone to Stay",
    artist: "Vancouver Sleep Clinic",
    img: "music-1",
    src: "Vancouver Sleep Clinic - Someone to Stay (Audio) - VSCVEVO",
  },
  {
    name: "Line Without a Hook",
    artist: "Ricky Montgomery",
    img: "music-1",
    src: "Ricky Montgomery - Line Without a Hook (Official Lyric Video) - Ricky Montgomery",
  },
  {
    name: "First Date",
    artist: "frad",
    img: "music-1",
    src: "music-2",
  },
  {
    name: "You'll Be Alright",
    artist: "Milky Day & frad & Hayne",
    img: "music-1",
    src: "Milky Day & frad & Hayne - You'll Be Alright - frad",
  },
  {
    name: "Glue Song",
    artist: "beabadoobee",
    img: "music-1",
    src: "beabadoobee - Glue Song (Lyrics) - Creative Chaos",
  },
  {
    name: "Love Story (Taylor’s Version)",
    artist: "Taylor Swift",
    img: "music-1",
    src: "Taylor Swift - Love Story (Taylor’s Version) [Official Lyric Video] - Taylor Swift",
  },
  {
    name: "To The Bone",
    artist: "Pamungkas",
    img: "music-1",
    src: "To The Bone - Pamungkas (Lirik Lagu & Terjemahan) - Mars Lirik",
  },
  {
    name: "Wildflower",
    artist: "Yung Kai",
    img: "music-1",
    src: "Wildflower - Yung Kai (lyrics)  mood edits - Mood Edits",
  },
  {
    name: "blue",
    artist: "yung kai",
    img: "music-1",
    src: "yung kai - blue (Lyrics) - Creative Chaos",
  },
  {
    name: "do you think you could love me",
    artist: "yung kai",
    img: "music-1",
    src: "yung kai - do you think you could love me (official lyric video) - yung kai",
  },
  {
    name: "Beautiful In White",
    artist: "Shane Filan",
    img: "music-1",
    src: "Shane Filan - Beautiful In White (Official Video) - ShaneFilanVEVO",
  },
  {
    name: "A Thousand Years",
    artist: "Christina Perri",
    img: "music-1",
    src: "Christina Perri - A Thousand Years [Official Music Video] - Christina Perri",
  },
  {
    name: "coldbrew",
    artist: "simple.",
    img: "music-1",
    src: "simple. - coldbrew",
  },
  {
    name: "i've always loved you",
    artist: "Arash Buana",
    img: "music-1",
    src: "Arash Buana - i've always loved you (Official Lyric Video) - Arash Buana",
  },
  {
    name: "Enchanted",
    artist: "Taylor Swift",
    img: "music-1",
    src: "Enchanted - Taylor Swift",
  },
  {
    name: "Until I Found You (Em Beihold Version)",
    artist: "Stephen Sanchez",
    img: "music-1",
    src: "Until I Found You (Em Beihold Version) - Stephen Sanchez",
  },
];
